### ISSUE TITLE
[WindiCSS] Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by Saektide** [PurotoApp/shelter#4]
## Machine info
* OS: Windows 7 (SP1)
* Node version: 14.16.1
* Yarn version: 1.22.17

## Error trace
```bash
 ERROR  Right-hand side of 'instanceof' is not an object

  at node_modules\nuxt-windicss\dist\index.js:62319:40
  at Array.find (<anonymous>)
  at WebpackBundler.<anonymous> (node_modules\nuxt-windicss\dist\index.js:62319:26)
  at WebpackBundler.<anonymous> (node_modules\@nuxt\kit\dist\index.js:818:25)
  at WebpackBundler.<anonymous> (node_modules\@nuxt\utils\dist\utils.js:668:29)
  at WebpackBundler.<anonymous> (node_modules\@nuxt\utils\dist\utils.js:668:29)
  at WebpackClientConfig.extendConfig (node_modules\@nuxt\webpack\dist\webpack.js:1509:37)
  at WebpackClientConfig.config (node_modules\@nuxt\webpack\dist\webpack.js:1544:50)
  at WebpackClientConfig.config (node_modules\@nuxt\webpack\dist\webpack.js:1708:26)
  at WebpackBundler.getWebpackConfig (node_modules\@nuxt\webpack\dist\webpack.js:2016:19)
  at WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2023:12)
  at Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:30)
  at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:107:5)
  at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:65:7)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
```

**Comment by Saektide** [comment]
Solved upgrading the `nuxt-windicss` package to `^2`.
